// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlkrsQozuM19nEmX86mfFQega2m1aF9g4',
    appId: '1:290564573613:android:0e85d01c402cf11d12b924',
    messagingSenderId: '290564573613',
    projectId: 'wechat-a6abe',
    storageBucket: 'wechat-a6abe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMrAKpdFIH7gCuYTgK22gmqXFWevHVlBQ',
    appId: '1:290564573613:ios:de3ea8c510227f3612b924',
    messagingSenderId: '290564573613',
    projectId: 'wechat-a6abe',
    storageBucket: 'wechat-a6abe.appspot.com',
    iosBundleId: 'com.example.weChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMrAKpdFIH7gCuYTgK22gmqXFWevHVlBQ',
    appId: '1:290564573613:ios:de3ea8c510227f3612b924',
    messagingSenderId: '290564573613',
    projectId: 'wechat-a6abe',
    storageBucket: 'wechat-a6abe.appspot.com',
    iosBundleId: 'com.example.weChatApp',
  );
}
